  


-- Dans le domaine



use widesign;



-- Données de la base widesign


INSERT INTO IMAGES (images) VALUES ( 'portrait');
INSERT INTO IMAGES (images) VALUES ( 'paysage');
INSERT INTO IMAGES (images) VALUES ( 'flyer');




INSERT INTO COLORS(Colors) VALUES ('blue');
INSERT INTO COLORS(Colors) VALUES ('original');
INSERT INTO COLORS(Colors) VALUES ('blacknwhite');
INSERT INTO COLORS(Colors) VALUES ('sepian');
INSERT INTO COLORS(Colors) VALUES ('mono');
INSERT INTO COLORS(Colors) VALUES ('dramatic');
INSERT INTO COLORS(Colors) VALUES ('argentic');


INSERT INTO SHIPPINGS(shipping) VALUES (1);
INSERT INTO SHIPPINGS(shipping) VALUES (2);
INSERT INTO SHIPPINGS(shipping) VALUES (3);
INSERT INTO SHIPPINGS(shipping) VALUES (4);
INSERT INTO SHIPPINGS(shipping) VALUES (5);

INSERT INTO SHIPPINGS(shipp) VALUES ('2019-03-27');
INSERT INTO SHIPPINGS(shipp) VALUES ('2019-06-28');
INSERT INTO SHIPPINGS(shipp) VALUES ('2019-08-15');
INSERT INTO SHIPPINGS(shipp) VALUES ('2019-09-22');
INSERT INTO SHIPPINGS(shipp) VALUES ('2019-03-25');

INSERT INTO CUSTOMERS(nom,prenom) VALUES ('Tochgaly','Etienne');
INSERT INTO CUSTOMERS(nom,prenom) VALUES ('Fabrice','Jacques');
INSERT INTO CUSTOMERS(nom,prenom) VALUES ('widby','Armand');
INSERT INTO CUSTOMERS(nom,prenom) VALUES ('Mark','Jean');
INSERT INTO CUSTOMERS(nom,prenom) VALUES ('Armand','Widby');
INSERT INTO CUSTOMERS(nom,prenom) VALUES ('Sadissou','Abbas');
INSERT INTO CUSTOMERS(nom,prenom) VALUES ('Joseph','Jhon');
INSERT INTO CUSTOMERS(nom,prenom) VALUES ('Pierre','Magalie');

INSERT INTO PRICES(prices) VALUES (80);
INSERT INTO PRICES(prices) VALUES (70);
INSERT INTO PRICES(prices) VALUES (60);
INSERT INTO PRICES(prices) VALUES (50);
INSERT INTO PRICES(prices) VALUES (40);
INSERT INTO PRICES(prices) VALUES (30);
INSERT INTO PRICES(prices) VALUES (20);
INSERT INTO PRICES(prices) VALUES (85);
INSERT INTO PRICES(prices) VALUES (75);
INSERT INTO PRICES(prices) VALUES (65);
INSERT INTO PRICES(prices) VALUES (55);
INSERT INTO PRICES(prices) VALUES (45);
INSERT INTO PRICES(prices) VALUES (35);
INSERT INTO PRICES(prices) VALUES (22);



